statefulset:
  # Deprecated field. Do not copy or you'll get coal for Christmas.
  podSecurityContext:
    runAsUser: 1111
    runAsGroup: 2222
    fsGroup: 3333
    fsGroupChangePolicy: "OnRootMismatch"

  securityContext:
    runAsUser: 4444
    runAsGroup: 5555
    fsGroup: 6666
    fsGroupChangePolicy: "OnRootMismatch"
