name: Test Redpanda Chart

on:
  workflow_call:
    inputs: {}
    secrets: {}

defaults:
  run:
    shell: nix develop --impure --command bash {0}

jobs:
  integration-redpanda-tests:
    name: "Run integration tests"
    runs-on: ubuntu-22.04
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_SM_READONLY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SM_READONLY_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: get secrets from aws sm
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,sdlc/prod/github/redpanda_sample_license
          parse-json-secrets: true
      - uses: cachix/install-nix-action@V27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      # Cache the nix store.
      - uses: DeterminateSystems/magic-nix-cache-action@v7

      # Cache helm repositories.
      - uses: actions/cache@v4
        with:
          key: helm-repositories
          path: |
            ~/.cache/helm

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create kind cluster
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
        with:
          config: .github/kind.yaml

      - name: Check kind config worked
        run: kubectl get nodes

      - name: Run integration tests
        env:
          REDPANDA_LICENSE: ${{ env.REDPANDA_SAMPLE_LICENSE }}
        run: |
          go test ./charts/redpanda/... -v
